name: Build and Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_DB: cineclubdb
          POSTGRES_USER: cineclubuser
          POSTGRES_PASSWORD: cineclubpwd
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U cineclubuser -d cineclubdb"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 10
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Run tests
        env:
          DB_NAME: cineclubdb
          DB_USERNAME: cineclubuser
          DB_PASSWORD: cineclubpwd
          DB_HOST: localhost
          DB_PORT: 5432
          JWT_SECRET: dce6efc6447f20e4ded3a58e84bb5d431baaa2186e42b7cfd16f8314126852f2
          JWT_ACCESS_EXPIRATION: 900000
          JWT_REFRESH_EXPIRATION: 604800000
        run: mvn test

      - name: Build JAR
        run: mvn package -DskipTests

      # On force le nom d'image en minuscules (GHCR refuse les majuscules)
      - name: Normalize image name (lowercase)
        run: echo "IMAGE_NAME=$(echo '${{ env.IMAGE_NAME }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Build Docker image
        run: docker build -t $IMAGE_NAME .

      - name: Push Docker image
        run: docker push $IMAGE_NAME

      - name: Trigger Render deploy
        run: curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"